name: msvc

on:
  push:

jobs:
  install-msvc:
    runs-on: windows-2022
    steps:
      - name: Download Visual Studio Build Tools
        run: |
          curl -L -o vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe
          # curl -L -o vs_buildtools.exe https://aka.ms/vs/17/release.ltsc.17.10/vs_buildtools.exe

      - name: Run bootstrapper
        timeout-minutes: 30
        run: |
          $process = Start-Process -FilePath ".\vs_buildtools.exe" `
            -ArgumentList @(
              '--installPath', '$PWD\vs-install',
              '--add', 'Microsoft.VisualStudio.Component.VC.14.44.17.14.x86.x64',
              '--includeRecommended',
              '--noUpdateInstaller',
              '--quiet',
              '--norestart'
            ) `
            -NoNewWindow `
            -PassThru `
            -Wait

          Write-Host "Process exited with code: $($process.ExitCode)"
          exit $process.ExitCode

      - name: Verify installation
        run: |
          if (Test-Path "$PWD\vs-install") {
            Write-Host "Installation directory exists"
            Get-ChildItem "$PWD\vs-install" | Select-Object Name
            if (Test-Path "$PWD\vs-install\VC\Tools\MSVC") {
              Write-Host "VCTools installed successfully"
              ls
              # if (Test-Path "$PWD\vs-install\VC\Tools\MSVC\14.40.33807") {
              #   Write-Host "14.40.33807 installed"
              #   & "$PWD\vs-install\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe"
              # }
            } else {
              Write-Host "VCTools NOT found"
              exit 1
            }
          } else {
            Write-Host "Installation directory does NOT exist"
            exit 1
          }
